const KEY="nikRoznamchaData";
const defaultData={settings:{lang:"fa",shopName:"روزنامچه نیک",currency:"؋"},products:[],sales:[],purchases:[],debtors:[],expenses:[]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaultData);
let state={page:"dashboard",modal:null,editing:null,search:"",printSale:null};

const T={
fa:{dashboard:"داشبورد",sales:"فروش",purchases:"خرید",inventory:"موجودی",debtors:"قرضدار",expenses:"مصارف",reports:"گزارش‌ها",settings:"تنظیمات",todaySales:"فروش امروز",todayPurchases:"خرید امروز",todayExpenses:"مصارف امروز",todayProfit:"سود تقریبی امروز",totalDebt:"مجموع قرضدار",lowStock:"موجودی کم",newSale:"+ فروش جدید",newPurchase:"+ خرید جدید",newProduct:"+ جنس جدید",newExpense:"+ مصرف جدید",newDebtor:"+ قرضدار جدید",product:"جنس",qty:"تعداد",buyPrice:"قیمت خرید",sellPrice:"قیمت فروش",customer:"مشتری",supplier:"فروشنده",payment:"پرداخت",cash:"نقدی",credit:"قرض",total:"مجموع",discount:"تخفیف",paid:"پرداخت‌شده",remaining:"باقی",date:"تاریخ",actions:"عملیات",save:"ذخیره",cancel:"لغو",print:"چاپ بل",view:"مشاهده",delete:"حذف",name:"نام",code:"کد",stock:"موجودی",minStock:"حداقل موجودی",expense:"مصرف",category:"دسته‌بندی",note:"یادداشت",reportsTitle:"گزارش‌های مالی",daily:"امروز",weekly:"این هفته",monthly:"این ماه",profit:"سود",purchasesTotal:"مجموع خرید",expensesTotal:"مجموع مصارف",salesTotal:"مجموع فروش",noData:"اطلاعاتی موجود نیست",language:"زبان",shopName:"نام دکان",saveSettings:"ذخیره تنظیمات",search:"جستجو",close:"بستن",billNo:"شماره بل",subtotal:"جمع",debt:"قرض",paidNow:"مبلغ پرداختی",addItem:"افزودن جنس",remove:"حذف",dashboardTitle:"خلاصه کسب‌وکار شما",lowStockTitle:"اجناس رو به اتمام",recentSales:"فروش‌های اخیر",expenseName:"عنوان مصرف",amount:"مبلغ",debtorName:"نام شخص",balance:"باقی حساب",paymentAdd:"ثبت پرداخت",paymentAmount:"مبلغ پرداخت",purchase:"خرید",sale:"فروش",all:"همه",confirmDelete:"حذف شود؟",printPaper:"بل آماده چاپ است",noItems:"حداقل یک جنس اضافه کنید"},
ps:{dashboard:"ډشبورډ",sales:"خرڅلاو",purchases:"پېرود",inventory:"زېرمه",debtors:"پوروړي",expenses:"لګښتونه",reports:"راپورونه",settings:"تنظیمات",todaySales:"د نن خرڅلاو",todayPurchases:"د نن پېرود",todayExpenses:"د نن لګښتونه",todayProfit:"د نن اټکلي ګټه",totalDebt:"ټول پور",lowStock:"کمه زېرمه",newSale:"+ نوی خرڅلاو",newPurchase:"+ نوی پېرود",newProduct:"+ نوی جنس",newExpense:"+ نوی لګښت",newDebtor:"+ نوی پوروړی",product:"جنس",qty:"تعداد",buyPrice:"د پېرود بیه",sellPrice:"د خرڅلاو بیه",customer:"پېرودونکی",supplier:"پلورونکی",payment:"تادیه",cash:"نغدي",credit:"پور",total:"ټول",discount:"تخفیف",paid:"ورکړل شوی",remaining:"پاتې",date:"نېټه",actions:"کړنې",save:"ساتل",cancel:"لغوه",print:"د بل چاپ",view:"کتل",delete:"حذف",name:"نوم",code:"کوډ",stock:"زېرمه",minStock:"لږ تر لږه زېرمه",expense:"لګښت",category:"کټګوري",note:"یادښت",reportsTitle:"مالي راپورونه",daily:"نن",weekly:"دا اونۍ",monthly:"دا میاشت",profit:"ګټه",purchasesTotal:"ټول پېرود",expensesTotal:"ټول لګښتونه",salesTotal:"ټول خرڅلاو",noData:"معلومات نشته",language:"ژبه",shopName:"د دوکان نوم",saveSettings:"تنظیمات ساتل",search:"لټون",close:"بندول",billNo:"د بل شمېره",subtotal:"ټول",debt:"پور",paidNow:"ورکړل شوی مبلغ",addItem:"جنس زیاتول",remove:"حذف",dashboardTitle:"ستاسې د کاروبار لنډیز",lowStockTitle:"د ختمېدو په حال کې اجناس",recentSales:"وروستي خرڅلاو",expenseName:"د لګښت نوم",amount:"مبلغ",debtorName:"د شخص نوم",balance:"پاتې حساب",paymentAdd:"د تادیې ثبت",paymentAmount:"د تادیې مبلغ",purchase:"پېرود",sale:"خرڅلاو",all:"ټول",confirmDelete:"حذف شي؟",printPaper:"بل د چاپ لپاره تیار دی",noItems:"لږ تر لږه یو جنس زیات کړئ"},
en:{dashboard:"Dashboard",sales:"Sales",purchases:"Purchases",inventory:"Inventory",debtors:"Debtors",expenses:"Expenses",reports:"Reports",settings:"Settings",todaySales:"Today's sales",todayPurchases:"Today's purchases",todayExpenses:"Today's expenses",todayProfit:"Estimated profit today",totalDebt:"Total debt",lowStock:"Low stock",newSale:"+ New sale",newPurchase:"+ New purchase",newProduct:"+ New product",newExpense:"+ New expense",newDebtor:"+ New debtor",product:"Product",qty:"Qty",buyPrice:"Buy price",sellPrice:"Sell price",customer:"Customer",supplier:"Supplier",payment:"Payment",cash:"Cash",credit:"Credit",total:"Total",discount:"Discount",paid:"Paid",remaining:"Remaining",date:"Date",actions:"Actions",save:"Save",cancel:"Cancel",print:"Print bill",view:"View",delete:"Delete",name:"Name",code:"Code",stock:"Stock",minStock:"Min stock",expense:"Expense",category:"Category",note:"Note",reportsTitle:"Financial reports",daily:"Today",weekly:"This week",monthly:"This month",profit:"Profit",purchasesTotal:"Purchases",expensesTotal:"Expenses",salesTotal:"Sales",noData:"No data",language:"Language",shopName:"Shop name",saveSettings:"Save settings",search:"Search",close:"Close",billNo:"Bill no.",subtotal:"Subtotal",debt:"Debt",paidNow:"Paid",addItem:"Add item",remove:"Remove",dashboardTitle:"Your business summary",lowStockTitle:"Low stock items",recentSales:"Recent sales",expenseName:"Expense title",amount:"Amount",debtorName:"Person name",balance:"Balance",paymentAdd:"Record payment",paymentAmount:"Payment amount",purchase:"Purchase",sale:"Sale",all:"All",confirmDelete:"Delete?",printPaper:"Bill ready to print",noItems:"Add at least one item"}
};

T.fa=Object.assign(T.fa,{welcome:"خوش آمدید",overview:"نمای کلی امروز",quickActions:"دسترسی سریع",recentSalesTitle:"آخرین فروش‌ها",lowStockTitle:"نیازمند توجه",viewAll:"مشاهده همه",today:"امروز",creator:"سازنده برنامه",purpose:"هدف ساخت",aboutText:"ایجاد سهولت در کار و مدیریت روزمره کسب‌وکارها و ساده‌تر شدن حسابداری دکان‌ها.",phone:"شماره تماس",email:"ایمیل",birthDate:"تاریخ تولد",aboutApp:"درباره روزنامچه نیک",appVersion:"نسخه 2.0 • طراحی جدید",navMenu:"منوی اصلی"});
T.ps=Object.assign(T.ps,{welcome:"ښه راغلاست",overview:"د نن لنډیز",quickActions:"چټک کارونه",recentSalesTitle:"وروستي خرڅلاوونه",viewAll:"ټول وګورئ",today:"نن",creator:"د پروګرام جوړونکی",purpose:"د جوړولو موخه",aboutText:"د کاروبار د ورځنیو چارو او حسابدارۍ د مدیریت اسانتیا.",phone:"د اړیکې شمېره",email:"برېښنالیک",birthDate:"د زېږون نېټه",aboutApp:"د نیک ورځنامچه په اړه",appVersion:"نسخه 2.0 • نوی ډیزاین",navMenu:"اصلي مېنو"});
T.en=Object.assign(T.en,{welcome:"Welcome",overview:"Today’s overview",quickActions:"Quick actions",recentSalesTitle:"Recent sales",viewAll:"View all",today:"Today",creator:"App creator",purpose:"Purpose",aboutText:"Making everyday business management and shop accounting simpler and easier.",phone:"Phone",email:"Email",birthDate:"Birth date",aboutApp:"About Nik Roznamcha",appVersion:"Version 2.0 • New design",navMenu:"Main menu"});
T.fa.phone=T.fa.phone||"شماره تماس";T.ps.phone=T.ps.phone||"د اړیکې شمېره";T.en.phone=T.en.phone||"Phone";
function t(k){return (T[data.settings.lang]||T.fa)[k]||k}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function money(n){return Number(n||0).toLocaleString()+" "+data.settings.currency}
function today(){return new Date().toISOString().slice(0,10)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function sum(a,fn){return a.reduce((x,y)=>x+Number(fn(y)||0),0)}
function icon(name,size=20){
 const paths={
  dashboard:'<path d="M3 13h8V3H3v10Zm10 8h8V3h-8v18ZM3 21h8v-6H3v6Z"/>',
  sales:'<path d="M6 2h9l3 3v17H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2Z"/><path d="M14 2v4h4M8 11h8M8 15h6"/>',
  purchases:'<path d="M3 7h18M6 3v4M18 3v4M5 7h14l1 13H4L5 7Z"/><path d="M9 12h6M9 16h6"/>',
  inventory:'<path d="m12 3 8 4-8 4-8-4 8-4Z"/><path d="m4 12 8 4 8-4M4 17l8 4 8-4"/>',
  debtors:'<circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
  expenses:'<path d="M5 21h14M12 3v14M8 7l4-4 4 4"/>',
  reports:'<path d="M4 19V5M4 19h16"/><path d="m7 15 3-4 3 2 5-7"/>',
  settings:'<path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.9 1.9-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6V21h-2.7v-.2a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1-1.9-1.9.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.6-1H4v-2.7h.2a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.9-1.9.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6V4H13v.2a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.9 1.9-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2V13h-.2a1.7 1.7 0 0 0-1.7 1.9Z"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  receipt:'<path d="M5 3h14v18l-3-2-4 2-4-2-3 2V3Z"/><path d="M8 8h8M8 12h8M8 16h5"/>',
  box:'<path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/>',
  wallet:'<path d="M4 6h15a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M2 8h19M16 13h3"/>',
  arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',
  alert:'<path d="M12 3 2.5 20h19L12 3Z"/><path d="M12 9v5M12 17h.01"/>',
  calendar:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M16 2v4M8 2v4M3 9h18"/>',
  user:'<circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
  mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',
  phone:'<path d="M7 3h3l1 5-2 1a15 15 0 0 0 5 5l1-2 5 1v3a2 2 0 0 1-2 2C10 18 6 14 4 7a2 2 0 0 1 2-2Z"/>',
  close:'<path d="m6 6 12 12M18 6 6 18"/>',
  printer:'<path d="M6 9V3h12v6M6 17H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-2M6 14h12v7H6v-7Z"/>',
  search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'
 };
 return `<svg class="icon" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.dashboard}</svg>`;
}
function navItems(){return [["dashboard","dashboard"],["sales","sales"],["purchases","purchases"],["inventory","inventory"],["debtors","debtors"],["expenses","expenses"],["reports","reports"],["settings","settings"]]}
function render(){
 document.documentElement.lang=data.settings.lang; document.documentElement.dir=data.settings.lang==="en"?"ltr":"rtl";
 const app=document.getElementById("app");
 const nav=navItems().map(([p,i])=>`<button class="nav-item ${state.page===p?"active":""}" onclick="go('${p}')"><span class="nav-icon">${icon(i,19)}</span><span>${t(p)}</span></button>`).join("");
 const mobileNav=navItems().slice(0,5).map(([p,i])=>`<button class="mobile-nav-item ${state.page===p?"active":""}" onclick="go('${p}')">${icon(i,20)}<span>${t(p)}</span></button>`).join("");
 app.innerHTML=`
 <div class="app-shell">
   <aside class="sidebar">
     <div class="brand-block"><div class="brand-mark">N</div><div><div class="brand-name">روزنامچه نیک</div><div class="brand-sub">Nik Roznamcha</div></div></div>
     <div class="nav-label">${t("navMenu")}</div>
     <nav class="nav">${nav}</nav>
     <div class="sidebar-footer"><div class="mini-status"><span class="status-dot"></span><span>${t("appVersion")}</span></div></div>
   </aside>
   <main class="main">
     <header class="topbar">
       <div class="topbar-title"><div class="mobile-brand-mark">N</div><div><div class="eyebrow">${data.settings.shopName||"روزنامچه نیک"}</div><h1>${pageTitle()}</h1></div></div>
       <div class="topbar-actions"><div class="lang-switch">${[["fa","دری"],["ps","پښتو"],["en","EN"]].map(([l,label])=>`<button class="lang-btn ${data.settings.lang===l?"active":""}" onclick="setLang('${l}')">${label}</button>`).join("")}</div></div>
     </header>
     <div class="content">${pageBody()}</div>
   </main>
   <nav class="mobile-nav">${mobileNav}<button class="mobile-nav-item ${["reports","settings"].includes(state.page)?"active":""}" onclick="go('${state.page==="settings"?"settings":"reports"}')">${icon(state.page==="settings"?"settings":"reports",20)}<span>${t(state.page==="settings"?"settings":"reports")}</span></button></nav>
 </div>${state.modal?modalHTML():""}${state.printSale?billHTML(state.printSale):""}`;
}
function pageTitle(){return state.page==="dashboard"?t("overview"):t(state.page)}
function go(p){state.page=p;state.modal=null;state.printSale=null;render()}
function setLang(l){data.settings.lang=l;save();render()}
function stats(){
 const d=today(), ss=data.sales.filter(x=>x.date===d), pp=data.purchases.filter(x=>x.date===d), ee=data.expenses.filter(x=>x.date===d);
 const sales=sum(ss,x=>x.total), purchases=sum(pp,x=>x.total), expenses=sum(ee,x=>x.amount);
 return {sales,purchases,expenses,profit:sales-purchases-expenses,debt:sum(data.debtors,x=>x.balance)}
}
function pageBody(){
 if(state.page==="dashboard")return dashboard();
 if(state.page==="sales")return salesPage();
 if(state.page==="purchases")return purchasesPage();
 if(state.page==="inventory")return inventoryPage();
 if(state.page==="debtors")return debtorsPage();
 if(state.page==="expenses")return expensesPage();
 if(state.page==="reports")return reportsPage();
 return settingsPage();
}
function dashboard(){
 const s=stats(), low=data.products.filter(p=>Number(p.stock)<=Number(p.minStock||0));
 const dateLabel=new Intl.DateTimeFormat(data.settings.lang==="en"?"en-US":data.settings.lang==="ps"?"ps-AF":"fa-AF",{weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(new Date());
 return `<section class="welcome-card"><div><span class="eyebrow light">${t("welcome")}</span><h2>${esc(data.settings.shopName||"روزنامچه نیک")}</h2><p>${t("overview")} · ${dateLabel}</p></div><button class="hero-action" onclick="openModal('sale')">${icon("plus",18)} ${t("newSale")}</button></section>
 <section class="stats-grid">
   ${statCard("sales",t("todaySales"),money(s.sales),"sales")}
   ${statCard("purchases",t("todayPurchases"),money(s.purchases),"purchases")}
   ${statCard("expenses",t("todayExpenses"),money(s.expenses),"expenses")}
   ${statCard("profit",t("todayProfit"),money(s.profit),"reports")}
 </section>
 <section class="section-block"><div class="section-title"><div><span class="eyebrow">${t("quickActions")}</span><h3>${t("quickActions")}</h3></div></div><div class="quick-grid">
   ${quickAction("sales","newSale","sale")}${quickAction("purchases","newPurchase","purchase")}${quickAction("inventory","newProduct","product")}${quickAction("expenses","newExpense","expense")}
 </div></section>
 <section class="dashboard-two-col">
   <div class="panel"><div class="panel-head"><div><span class="eyebrow">${t("lowStock")}</span><h3>${t("lowStockTitle")}</h3></div><button class="text-btn" onclick="go('inventory')">${t("viewAll")} ${icon("arrow",15)}</button></div>${low.length?`<div class="attention-list">${low.slice(0,5).map(p=>`<div class="attention-row"><div class="item-leading"><span class="item-icon warning">${icon("alert",18)}</span><div><b>${esc(p.name)}</b><small>${t("minStock")}: ${p.minStock}</small></div></div><strong>${p.stock}</strong></div>`).join("")}</div>`:`<div class="empty-state">${icon("inventory",24)}<span>${t("noData")}</span></div>`}</div>
   <div class="panel"><div class="panel-head"><div><span class="eyebrow">${t("sales")}</span><h3>${t("recentSalesTitle")}</h3></div><button class="text-btn" onclick="go('sales')">${t("viewAll")} ${icon("arrow",15)}</button></div>${salesMini(data.sales.slice(-5).reverse())}</div>
 </section>`;
}
function statCard(key,label,value,ico){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon ${key}">${icon(ico,19)}</span></div><strong>${value}</strong><div class="stat-meta">${t("today")}</div></div>`}
function quickAction(ico,key,modal){return `<button class="quick-action" onclick="openModal('${modal}')"><span class="quick-icon">${icon(ico,21)}</span><span>${t(key)}</span><span class="quick-arrow">${icon("arrow",16)}</span></button>`}
function salesMini(arr){if(!arr.length)return `<div class="empty-state">${icon("receipt",24)}<span>${t("noData")}</span></div>`;return `<div class="mini-list">${arr.map(x=>`<div class="mini-row"><div class="mini-main"><span class="avatar">${icon("receipt",17)}</span><div><b>${esc(x.customer||t("cash"))}</b><small>${x.billNo} · ${x.date}</small></div></div><strong>${money(x.total)}</strong></div>`).join("")}</div>`}
function stat(label,value){return statCard("neutral",label,value,"reports")}
function salesRows(arr){if(!arr.length)return `<div class="empty-state">${icon("receipt",24)}<span>${t("noData")}</span></div>`;return `<div class="table-wrap"><table class="table"><thead><tr><th>${t("billNo")}</th><th>${t("date")}</th><th>${t("customer")}</th><th>${t("total")}</th><th>${t("payment")}</th><th>${t("actions")}</th></tr></thead><tbody>${arr.map(x=>`<tr><td><span class="bill-tag">${x.billNo}</span></td><td>${x.date}</td><td>${esc(x.customer||"-")}</td><td><strong>${money(x.total)}</strong></td><td><span class="badge ${x.payment==="cash"?"green":"amber"}">${x.payment==="cash"?t("cash"):t("credit")}</span></td><td class="actions"><button class="icon-btn" title="${t("print")}" onclick="printSale('${x.id}')">${icon("printer",17)}</button><button class="icon-btn danger" title="${t("delete")}" onclick="delSale('${x.id}')">${icon("close",17)}</button></td></tr>`).join("")}</tbody></table></div>`}
function pageToolbar(buttonText,modal,search=false){return `<div class="page-toolbar"><div>${search?`<div class="search-box">${icon("search",18)}<input placeholder="${t("search")}" oninput="state.search=this.value;render()"></div>`:""}</div><button class="btn primary" onclick="openModal('${modal}')">${icon("plus",17)} ${buttonText}</button></div>`}
function salesPage(){return `${pageToolbar(t("newSale"),"sale",true)}${salesRows([...data.sales].reverse())}`}
function purchasesPage(){return `${pageToolbar(t("newPurchase"),"purchase",true)}<div class="table-wrap"><table class="table"><thead><tr><th>${t("date")}</th><th>${t("supplier")}</th><th>${t("product")}</th><th>${t("qty")}</th><th>${t("total")}</th><th>${t("payment")}</th><th>${t("actions")}</th></tr></thead><tbody>${data.purchases.length?data.purchases.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.supplier||"-")}</td><td>${esc(x.productName)}</td><td>${x.qty}</td><td><strong>${money(x.total)}</strong></td><td><span class="badge ${x.payment==="cash"?"green":"amber"}">${x.payment==="cash"?t("cash"):t("credit")}</span></td><td><button class="icon-btn danger" onclick="delPurchase('${x.id}')">${icon("close",17)}</button></td></tr>`).join(""):`<tr><td colspan="7"><div class="empty-state">${icon("box",24)}<span>${t("noData")}</span></div></td></tr>`}</tbody></table></div>`}
function inventoryPage(){return `${pageToolbar(t("newProduct"),"product",true)}<div class="table-wrap"><table class="table"><thead><tr><th>${t("name")}</th><th>${t("code")}</th><th>${t("stock")}</th><th>${t("buyPrice")}</th><th>${t("sellPrice")}</th><th>${t("minStock")}</th><th>${t("actions")}</th></tr></thead><tbody>${data.products.length?data.products.map(p=>`<tr><td><div class="product-cell"><span class="product-dot">${icon("box",15)}</span><b>${esc(p.name)}</b></div></td><td>${esc(p.code||"-")}</td><td><span class="stock-value ${Number(p.stock)<=Number(p.minStock||0)?"low":""}">${p.stock}</span></td><td>${money(p.buyPrice)}</td><td><strong>${money(p.sellPrice)}</strong></td><td>${p.minStock}</td><td><button class="icon-btn danger" onclick="delProduct('${p.id}')">${icon("close",17)}</button></td></tr>`).join(""):`<tr><td colspan="7"><div class="empty-state">${icon("inventory",24)}<span>${t("noData")}</span></div></td></tr>`}</tbody></table></div>`}
function debtorsPage(){return `${pageToolbar(t("newDebtor"),"debtor",true)}<div class="table-wrap"><table class="table"><thead><tr><th>${t("name")}</th><th>${t("phone")||"شماره"}</th><th>${t("balance")}</th><th>${t("actions")}</th></tr></thead><tbody>${data.debtors.length?data.debtors.map(x=>`<tr><td><div class="product-cell"><span class="avatar small">${icon("user",15)}</span><b>${esc(x.name)}</b></div></td><td>${esc(x.phone||"-")}</td><td><span class="debt-value">${money(x.balance)}</span></td><td class="actions"><button class="btn small secondary" onclick="openPayment('${x.id}')">${icon("wallet",15)} ${t("paymentAdd")}</button><button class="icon-btn danger" onclick="delDebtor('${x.id}')">${icon("close",17)}</button></td></tr>`).join(""):`<tr><td colspan="4"><div class="empty-state">${icon("user",24)}<span>${t("noData")}</span></div></td></tr>`}</tbody></table></div>`}
function expensesPage(){return `${pageToolbar(t("newExpense"),"expense",true)}<div class="table-wrap"><table class="table"><thead><tr><th>${t("date")}</th><th>${t("expenseName")}</th><th>${t("amount")}</th><th>${t("note")}</th><th>${t("actions")}</th></tr></thead><tbody>${data.expenses.length?data.expenses.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.name)}</td><td><strong>${money(x.amount)}</strong></td><td>${esc(x.note||"-")}</td><td><button class="icon-btn danger" onclick="delExpense('${x.id}')">${icon("close",17)}</button></td></tr>`).join(""):`<tr><td colspan="5"><div class="empty-state">${icon("wallet",24)}<span>${t("noData")}</span></div></td></tr>`}</tbody></table></div>`}
function reportsPage(){const sales=sum(data.sales,x=>x.total), purchases=sum(data.purchases,x=>x.total), expenses=sum(data.expenses,x=>x.amount), profit=sales-purchases-expenses;return `<div class="stats-grid reports-grid">${statCard("sales",t("salesTotal"),money(sales),"sales")}${statCard("purchases",t("purchasesTotal"),money(purchases),"purchases")}${statCard("expenses",t("expensesTotal"),money(expenses),"expenses")}${statCard("profit",t("profit"),money(profit),"reports")}</div><div class="panel report-panel"><div class="panel-head"><div><span class="eyebrow">${t("monthly")}</span><h3>${t("reportsTitle")}</h3></div></div><div class="report-lines"><div><span>${t("salesTotal")}</span><b>${money(sales)}</b></div><div><span>${t("purchasesTotal")}</span><b>${money(purchases)}</b></div><div><span>${t("expensesTotal")}</span><b>${money(expenses)}</b></div><div class="total-line"><span>${t("profit")}</span><b>${money(profit)}</b></div></div></div>`}
function settingsPage(){return `<div class="settings-grid"><div class="panel"><div class="panel-head"><div><span class="eyebrow">${t("settings")}</span><h3>${t("shopName")}</h3></div><span class="panel-icon">${icon("settings",20)}</span></div><div class="form settings-form"><div class="field"><label>${t("shopName")}</label><input id="shopName" value="${esc(data.settings.shopName)}"></div><div class="field"><label>${t("language")}</label><select id="langSet"><option value="fa" ${data.settings.lang==="fa"?"selected":""}>دری</option><option value="ps" ${data.settings.lang==="ps"?"selected":""}>پښتو</option><option value="en" ${data.settings.lang==="en"?"selected":""}>English</option></select></div><div class="full"><button class="btn primary" onclick="saveSettings()">${icon("settings",17)} ${t("saveSettings")}</button></div></div></div><div class="panel about-panel"><div class="about-mark">N</div><span class="eyebrow">${t("aboutApp")}</span><h3>روزنامچه نیک</h3><p>${t("aboutText")}</p><div class="creator-list"><div><span>${icon("user",16)} ${t("creator")}</span><b>Ahmad Najeem Nik</b></div><div><span>${icon("calendar",16)} ${t("birthDate")}</span><b>1999/04</b></div><div><span>${icon("phone",16)} ${t("phone")}</span><b>+93783788278</b></div><div><span>${icon("mail",16)} ${t("email")}</span><b>a.najeemnik@gmail.com</b></div></div></div></div>`}
function modalHTML(){
 let content="",title="";
 if(state.modal==="product"){title=t("newProduct");content=`<form onsubmit="saveProduct(event)" class="form"><div class="field"><label>${t("name")}</label><input name="name" required></div><div class="field"><label>${t("code")}</label><input name="code"></div><div class="field"><label>${t("buyPrice")}</label><input name="buyPrice" type="number" min="0" required></div><div class="field"><label>${t("sellPrice")}</label><input name="sellPrice" type="number" min="0" required></div><div class="field"><label>${t("stock")}</label><input name="stock" type="number" min="0" value="0" required></div><div class="field"><label>${t("minStock")}</label><input name="minStock" type="number" min="0" value="2"></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="sale"){title=t("newSale");content=saleForm()}
 if(state.modal==="purchase"){title=t("newPurchase");content=`<form onsubmit="savePurchase(event)" class="form"><div class="field"><label>${t("product")}</label><select name="productId" required>${data.products.map(p=>`<option value="${p.id}">${esc(p.name)} (${p.stock})</option>`).join("")}</select></div><div class="field"><label>${t("qty")}</label><input name="qty" type="number" min="1" required></div><div class="field"><label>${t("buyPrice")}</label><input name="price" type="number" min="0" required></div><div class="field"><label>${t("supplier")}</label><input name="supplier"></div><div class="field"><label>${t("payment")}</label><select name="payment"><option value="cash">${t("cash")}</option><option value="credit">${t("credit")}</option></select></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="expense"){title=t("newExpense");content=`<form onsubmit="saveExpense(event)" class="form"><div class="field"><label>${t("expenseName")}</label><input name="name" required></div><div class="field"><label>${t("amount")}</label><input name="amount" type="number" min="0" required></div><div class="field full"><label>${t("note")}</label><input name="note"></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="debtor"){title=t("newDebtor");content=`<form onsubmit="saveDebtor(event)" class="form"><div class="field"><label>${t("name")}</label><input name="name" required></div><div class="field"><label>شماره تماس</label><input name="phone"></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="payment"){const d=data.debtors.find(x=>x.id===state.editing);title=t("paymentAdd");content=`<form onsubmit="savePayment(event)" class="form"><div class="notice">${esc(d?.name||"")} — ${money(d?.balance)}</div><div class="field full"><label>${t("paymentAmount")}</label><input name="amount" type="number" min="1" max="${d?.balance||0}" required></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 return `<div class="modal-back" onclick="if(event.target===this)closeModal()"><div class="modal"><button class="close" onclick="closeModal()">×</button><h3>${title}</h3>${content}</div></div>`
}
function saleForm(){return `<form onsubmit="saveSale(event)" class="form"><div class="field"><label>${t("product")}</label><select name="productId" required>${data.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.sellPrice)} (موجودی ${p.stock})</option>`).join("")}</select></div><div class="field"><label>${t("qty")}</label><input name="qty" type="number" min="1" required></div><div class="field"><label>${t("customer")}</label><input name="customer"></div><div class="field"><label>${t("payment")}</label><select name="payment"><option value="cash">${t("cash")}</option><option value="credit">${t("credit")}</option></select></div><div class="field"><label>${t("discount")}</label><input name="discount" type="number" min="0" value="0"></div><div class="field"><label>${t("paidNow")}</label><input name="paid" type="number" min="0" value="0"></div><div class="field full"><label>${t("note")}</label><input name="note"></div><div class="full"><button class="btn success">${t("save")} + ${t("print")}</button></div></form>`}
function openModal(m){state.modal=m;state.editing=null;render()}
function closeModal(){state.modal=null;render()}
function saveProduct(e){e.preventDefault();const f=new FormData(e.target);data.products.push({id:uid(),name:f.get("name"),code:f.get("code"),buyPrice:+f.get("buyPrice"),sellPrice:+f.get("sellPrice"),stock:+f.get("stock"),minStock:+f.get("minStock")});save();closeModal()}
function savePurchase(e){e.preventDefault();const f=new FormData(e.target),p=data.products.find(x=>x.id===f.get("productId"));if(!p)return;const qty=+f.get("qty"),price=+f.get("price");p.stock+=qty;data.purchases.push({id:uid(),date:today(),productId:p.id,productName:p.name,qty,total:qty*price,price,supplier:f.get("supplier"),payment:f.get("payment")});save();closeModal()}
function saveSale(e){e.preventDefault();const f=new FormData(e.target),p=data.products.find(x=>x.id===f.get("productId"));if(!p)return;if(p.stock<+f.get("qty")){alert("موجودی کافی نیست");return}const qty=+f.get("qty"),sub=qty*p.sellPrice,discount=+f.get("discount")||0,total=Math.max(0,sub-discount),paid=Math.min(total,+f.get("paid")||0),remaining=total-paid; p.stock-=qty; const sale={id:uid(),billNo:"NR-"+String(data.sales.length+1).padStart(5,"0"),date:today(),customer:f.get("customer"),productId:p.id,items:[{name:p.name,qty,price:p.sellPrice,total:qty*p.sellPrice}],subtotal:sub,discount,total,paid,remaining,payment:f.get("payment"),note:f.get("note")};data.sales.push(sale);if(remaining>0&&f.get("customer")){let d=data.debtors.find(x=>x.name.trim()===f.get("customer").trim());if(!d){d={id:uid(),name:f.get("customer"),balance:0,phone:""};data.debtors.push(d)}d.balance+=remaining}save();state.modal=null;state.printSale=sale;render();setTimeout(()=>window.print(),300)}
function saveExpense(e){e.preventDefault();const f=new FormData(e.target);data.expenses.push({id:uid(),date:today(),name:f.get("name"),amount:+f.get("amount"),note:f.get("note")});save();closeModal()}
function saveDebtor(e){e.preventDefault();const f=new FormData(e.target);data.debtors.push({id:uid(),name:f.get("name"),phone:f.get("phone"),balance:0});save();closeModal()}
function openPayment(id){state.editing=id;state.modal="payment";render()}
function savePayment(e){e.preventDefault();const f=new FormData(e.target),d=data.debtors.find(x=>x.id===state.editing);if(d)d.balance=Math.max(0,d.balance-(+f.get("amount")||0));save();closeModal()}
function delSale(id){if(!confirm(t("confirmDelete")))return;const s=data.sales.find(x=>x.id===id);if(s){s.items.forEach(i=>{const p=data.products.find(p=>p.name===i.name);if(p)p.stock+=i.qty});}data.sales=data.sales.filter(x=>x.id!==id);save();render()}
function delPurchase(id){if(!confirm(t("confirmDelete")))return;const x=data.purchases.find(x=>x.id===id),p=data.products.find(p=>p.id===x?.productId);if(p)p.stock=Math.max(0,p.stock-x.qty);data.purchases=data.purchases.filter(x=>x.id!==id);save();render()}
function delProduct(id){if(confirm(t("confirmDelete"))){data.products=data.products.filter(x=>x.id!==id);save();render()}}
function delDebtor(id){if(confirm(t("confirmDelete"))){data.debtors=data.debtors.filter(x=>x.id!==id);save();render()}}
function delExpense(id){if(confirm(t("confirmDelete"))){data.expenses=data.expenses.filter(x=>x.id!==id);save();render()}}
function saveSettings(){data.settings.shopName=document.getElementById("shopName").value;data.settings.lang=document.getElementById("langSet").value;save();render()}
function printSale(id){state.printSale=data.sales.find(x=>x.id===id);render();setTimeout(()=>window.print(),200)}
function billHTML(s){if(!s)return"";return `<div class="bill"><h2>${esc(data.settings.shopName)}</h2><p>${t("billNo")}: ${s.billNo}</p><p>${s.date}</p><table><tr><th>${t("product")}</th><th>${t("qty")}</th><th>${t("total")}</th></tr>${s.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.qty}</td><td>${money(i.total)}</td></tr>`).join("")}</table><p>${t("subtotal")}: ${money(s.subtotal)}</p><p>${t("discount")}: ${money(s.discount)}</p><p>${t("total")}: ${money(s.total)}</p><p>${t("paid")}: ${money(s.paid)}</p><p>${t("remaining")}: ${money(s.remaining)}</p><p>${esc(s.customer||"")}</p></div>`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
window.go=go;window.setLang=setLang;window.openModal=openModal;window.closeModal=closeModal;window.saveProduct=saveProduct;window.savePurchase=savePurchase;window.saveSale=saveSale;window.saveExpense=saveExpense;window.saveDebtor=saveDebtor;window.openPayment=openPayment;window.savePayment=savePayment;window.delSale=delSale;window.delPurchase=delPurchase;window.delProduct=delProduct;window.delDebtor=delDebtor;window.delExpense=delExpense;window.saveSettings=saveSettings;window.printSale=printSale;
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
render();