const KEY="nikRoznamchaData";
const defaultData={settings:{lang:"fa",shopName:"روزنامچه نیک",currency:"؋"},products:[],sales:[],purchases:[],debtors:[],expenses:[]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaultData);
let state={page:"dashboard",modal:null,editing:null,search:"",printSale:null};

const T={
fa:{dashboard:"داشبورد",sales:"فروش",purchases:"خرید",inventory:"موجودی",debtors:"قرضدار",expenses:"مصارف",reports:"گزارش‌ها",settings:"تنظیمات",todaySales:"فروش امروز",todayPurchases:"خرید امروز",todayExpenses:"مصارف امروز",todayProfit:"سود تقریبی امروز",totalDebt:"مجموع قرضدار",lowStock:"موجودی کم",newSale:"+ فروش جدید",newPurchase:"+ خرید جدید",newProduct:"+ جنس جدید",newExpense:"+ مصرف جدید",newDebtor:"+ قرضدار جدید",product:"جنس",qty:"تعداد",buyPrice:"قیمت خرید",sellPrice:"قیمت فروش",customer:"مشتری",supplier:"فروشنده",payment:"پرداخت",cash:"نقدی",credit:"قرض",total:"مجموع",discount:"تخفیف",paid:"پرداخت‌شده",remaining:"باقی",date:"تاریخ",actions:"عملیات",save:"ذخیره",cancel:"لغو",print:"چاپ بل",view:"مشاهده",delete:"حذف",name:"نام",code:"کد",stock:"موجودی",minStock:"حداقل موجودی",expense:"مصرف",category:"دسته‌بندی",note:"یادداشت",reportsTitle:"گزارش‌های مالی",daily:"امروز",weekly:"این هفته",monthly:"این ماه",profit:"سود",purchasesTotal:"مجموع خرید",expensesTotal:"مجموع مصارف",salesTotal:"مجموع فروش",noData:"اطلاعاتی موجود نیست",language:"زبان",shopName:"نام دکان",saveSettings:"ذخیره تنظیمات",search:"جستجو",close:"بستن",billNo:"شماره بل",subtotal:"جمع",debt:"قرض",paidNow:"مبلغ پرداختی",addItem:"افزودن جنس",remove:"حذف",dashboardTitle:"خلاصه کسب‌وکار شما",lowStockTitle:"اجناس رو به اتمام",recentSales:"فروش‌های اخیر",expenseName:"عنوان مصرف",amount:"مبلغ",debtorName:"نام شخص",balance:"باقی حساب",paymentAdd:"ثبت پرداخت",paymentAmount:"مبلغ پرداخت",purchase:"خرید",sale:"فروش",all:"همه",confirmDelete:"حذف شود؟",printPaper:"بل آماده چاپ است",noItems:"حداقل یک جنس اضافه کنید"},
ps:{dashboard:"ډشبورډ",sales:"خرڅلاو",purchases:"پېرود",inventory:"زېرمه",debtors:"پوروړي",expenses:"لګښتونه",reports:"راپورونه",settings:"تنظیمات",todaySales:"د نن خرڅلاو",todayPurchases:"د نن پېرود",todayExpenses:"د نن لګښتونه",todayProfit:"د نن اټکلي ګټه",totalDebt:"ټول پور",lowStock:"کمه زېرمه",newSale:"+ نوی خرڅلاو",newPurchase:"+ نوی پېرود",newProduct:"+ نوی جنس",newExpense:"+ نوی لګښت",newDebtor:"+ نوی پوروړی",product:"جنس",qty:"تعداد",buyPrice:"د پېرود بیه",sellPrice:"د خرڅلاو بیه",customer:"پېرودونکی",supplier:"پلورونکی",payment:"تادیه",cash:"نغدي",credit:"پور",total:"ټول",discount:"تخفیف",paid:"ورکړل شوی",remaining:"پاتې",date:"نېټه",actions:"کړنې",save:"ساتل",cancel:"لغوه",print:"د بل چاپ",view:"کتل",delete:"حذف",name:"نوم",code:"کوډ",stock:"زېرمه",minStock:"لږ تر لږه زېرمه",expense:"لګښت",category:"کټګوري",note:"یادښت",reportsTitle:"مالي راپورونه",daily:"نن",weekly:"دا اونۍ",monthly:"دا میاشت",profit:"ګټه",purchasesTotal:"ټول پېرود",expensesTotal:"ټول لګښتونه",salesTotal:"ټول خرڅلاو",noData:"معلومات نشته",language:"ژبه",shopName:"د دوکان نوم",saveSettings:"تنظیمات ساتل",search:"لټون",close:"بندول",billNo:"د بل شمېره",subtotal:"ټول",debt:"پور",paidNow:"ورکړل شوی مبلغ",addItem:"جنس زیاتول",remove:"حذف",dashboardTitle:"ستاسې د کاروبار لنډیز",lowStockTitle:"د ختمېدو په حال کې اجناس",recentSales:"وروستي خرڅلاو",expenseName:"د لګښت نوم",amount:"مبلغ",debtorName:"د شخص نوم",balance:"پاتې حساب",paymentAdd:"د تادیې ثبت",paymentAmount:"د تادیې مبلغ",purchase:"پېرود",sale:"خرڅلاو",all:"ټول",confirmDelete:"حذف شي؟",printPaper:"بل د چاپ لپاره تیار دی",noItems:"لږ تر لږه یو جنس زیات کړئ"},
en:{dashboard:"Dashboard",sales:"Sales",purchases:"Purchases",inventory:"Inventory",debtors:"Debtors",expenses:"Expenses",reports:"Reports",settings:"Settings",todaySales:"Today's sales",todayPurchases:"Today's purchases",todayExpenses:"Today's expenses",todayProfit:"Estimated profit today",totalDebt:"Total debt",lowStock:"Low stock",newSale:"+ New sale",newPurchase:"+ New purchase",newProduct:"+ New product",newExpense:"+ New expense",newDebtor:"+ New debtor",product:"Product",qty:"Qty",buyPrice:"Buy price",sellPrice:"Sell price",customer:"Customer",supplier:"Supplier",payment:"Payment",cash:"Cash",credit:"Credit",total:"Total",discount:"Discount",paid:"Paid",remaining:"Remaining",date:"Date",actions:"Actions",save:"Save",cancel:"Cancel",print:"Print bill",view:"View",delete:"Delete",name:"Name",code:"Code",stock:"Stock",minStock:"Min stock",expense:"Expense",category:"Category",note:"Note",reportsTitle:"Financial reports",daily:"Today",weekly:"This week",monthly:"This month",profit:"Profit",purchasesTotal:"Purchases",expensesTotal:"Expenses",salesTotal:"Sales",noData:"No data",language:"Language",shopName:"Shop name",saveSettings:"Save settings",search:"Search",close:"Close",billNo:"Bill no.",subtotal:"Subtotal",debt:"Debt",paidNow:"Paid",addItem:"Add item",remove:"Remove",dashboardTitle:"Your business summary",lowStockTitle:"Low stock items",recentSales:"Recent sales",expenseName:"Expense title",amount:"Amount",debtorName:"Person name",balance:"Balance",paymentAdd:"Record payment",paymentAmount:"Payment amount",purchase:"Purchase",sale:"Sale",all:"All",confirmDelete:"Delete?",printPaper:"Bill ready to print",noItems:"Add at least one item"}
};
function t(k){return (T[data.settings.lang]||T.fa)[k]||k}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function money(n){return Number(n||0).toLocaleString()+" "+data.settings.currency}
function today(){return new Date().toISOString().slice(0,10)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function sum(a,fn){return a.reduce((x,y)=>x+Number(fn(y)||0),0)}
function navItems(){return [["dashboard","⌂"],["sales","▣"],["purchases","↙"],["inventory","▤"],["debtors","👤"],["expenses","−"],["reports","▥"],["settings","⚙"]]}
function render(){
 document.documentElement.lang=data.settings.lang; document.documentElement.dir=data.settings.lang==="en"?"ltr":"rtl";
 const app=document.getElementById("app");
 app.innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><h1>روزنامچه نیک</h1><small>Nik Roznamcha</small></div><nav class="nav">${navItems().map(([p,i])=>`<button class="${state.page===p?"active":""}" onclick="go('${p}')"><b>${i}</b> <span>${t(p)}</span></button>`).join("")}</nav></aside><main class="main"><header class="top"><div><h2>${pageTitle()}</h2></div><div class="lang">${["fa","ps","en"].map(l=>`<button onclick="setLang('${l}')">${l==="fa"?"دری":l==="ps"?"پښتو":"EN"}</button>`).join("")}</div></header>${pageBody()}</main></div>${state.modal?modalHTML():""}${state.printSale?billHTML(state.printSale):""}`;
}
function pageTitle(){return state.page==="dashboard"?t("dashboardTitle"):t(state.page)}
function go(p){state.page=p;state.modal=null;render()}
function setLang(l){data.settings.lang=l;save();render()}
function stats(){
 const d=today(), ss=data.sales.filter(x=>x.date===d), pp=data.purchases.filter(x=>x.date===d), ee=data.expenses.filter(x=>x.date===d);
 const sales=sum(ss,x=>x.total), purchases=sum(pp,x=>x.total), expenses=sum(ee,x=>x.amount);
 return {sales,purchases,expenses,profit:sales-purchases-expenses,debt:sum(data.debtors,x=>x.balance)}
}
function pageBody(){
 if(state.page==="dashboard")return dashboard();
 if(state.page==="sales")return salesPage();
 if(state.page==="purchases")return purchasesPage();
 if(state.page==="inventory")return inventoryPage();
 if(state.page==="debtors")return debtorsPage();
 if(state.page==="expenses")return expensesPage();
 if(state.page==="reports")return reportsPage();
 return settingsPage();
}
function dashboard(){
 const s=stats(), low=data.products.filter(p=>Number(p.stock)<=Number(p.minStock||0));
 return `<div class="grid">${stat(t("todaySales"),money(s.sales))}${stat(t("todayPurchases"),money(s.purchases))}${stat(t("todayExpenses"),money(s.expenses))}${stat(t("todayProfit"),money(s.profit))}</div><div class="section"><div class="quick"><button onclick="openModal('sale')">💰 ${t("newSale")}</button><button onclick="openModal('purchase')">📦 ${t("newPurchase")}</button><button onclick="openModal('product')">➕ ${t("newProduct")}</button><button onclick="openModal('expense')">💸 ${t("newExpense")}</button></div></div><div class="section grid">${stat(t("totalDebt"),money(s.debt))}${stat(t("lowStock"),low.length)}</div><div class="section card"><div class="section-head"><h3>${t("lowStockTitle")}</h3></div>${low.length?`<div class="table-wrap"><table class="table"><tr><th>${t("product")}</th><th>${t("stock")}</th><th>${t("minStock")}</th></tr>${low.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.stock}</td><td>${p.minStock}</td></tr>`).join("")}</table></div>`:`<div class="empty">${t("noData")}</div>`}</div><div class="section card"><div class="section-head"><h3>${t("recentSales")}</h3><button class="btn small" onclick="go('sales')">${t("view")}</button></div>${salesRows(data.sales.slice(-5).reverse())}</div>`
}
function stat(label,value){return `<div class="card stat"><div class="label">${label}</div><div class="value">${value}</div></div>`}
function salesRows(arr){if(!arr.length)return `<div class="empty">${t("noData")}</div>`;return `<div class="table-wrap"><table class="table"><tr><th>${t("billNo")}</th><th>${t("date")}</th><th>${t("customer")}</th><th>${t("total")}</th><th>${t("payment")}</th><th>${t("actions")}</th></tr>${arr.map(x=>`<tr><td>${x.billNo}</td><td>${x.date}</td><td>${esc(x.customer||"-")}</td><td>${money(x.total)}</td><td>${x.payment==="cash"?t("cash"):t("credit")}</td><td class="actions"><button class="btn small" onclick="printSale('${x.id}')">${t("print")}</button><button class="btn small danger" onclick="delSale('${x.id}')">${t("delete")}</button></td></tr>`).join("")}</table></div>`}
function salesPage(){return `<div class="section-head"><button class="btn" onclick="openModal('sale')">${t("newSale")}</button></div>${salesRows([...data.sales].reverse())}`}
function purchasesPage(){return `<div class="section-head"><button class="btn" onclick="openModal('purchase')">${t("newPurchase")}</button></div><div class="table-wrap"><table class="table"><tr><th>${t("date")}</th><th>${t("supplier")}</th><th>${t("product")}</th><th>${t("qty")}</th><th>${t("total")}</th><th>${t("payment")}</th><th>${t("actions")}</th></tr>${data.purchases.length?data.purchases.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.supplier||"-")}</td><td>${esc(x.productName)}</td><td>${x.qty}</td><td>${money(x.total)}</td><td>${x.payment==="cash"?t("cash"):t("credit")}</td><td><button class="btn small danger" onclick="delPurchase('${x.id}')">${t("delete")}</button></td></tr>`).join(""):`<tr><td colspan="7" class="empty">${t("noData")}</td></tr>`}</table></div>`}
function inventoryPage(){return `<div class="section-head"><button class="btn" onclick="openModal('product')">${t("newProduct")}</button></div><div class="table-wrap"><table class="table"><tr><th>${t("name")}</th><th>${t("code")}</th><th>${t("stock")}</th><th>${t("buyPrice")}</th><th>${t("sellPrice")}</th><th>${t("minStock")}</th><th>${t("actions")}</th></tr>${data.products.length?data.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.code||"-")}</td><td>${p.stock}</td><td>${money(p.buyPrice)}</td><td>${money(p.sellPrice)}</td><td>${p.minStock}</td><td><button class="btn small danger" onclick="delProduct('${p.id}')">${t("delete")}</button></td></tr>`).join(""):`<tr><td colspan="7" class="empty">${t("noData")}</td></tr>`}</table></div>`}
function debtorsPage(){return `<div class="section-head"><button class="btn" onclick="openModal('debtor')">${t("newDebtor")}</button></div><div class="table-wrap"><table class="table"><tr><th>${t("name")}</th><th>${t("phone")||"شماره"}</th><th>${t("balance")}</th><th>${t("actions")}</th></tr>${data.debtors.length?data.debtors.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone||"-")}</td><td>${money(x.balance)}</td><td class="actions"><button class="btn small" onclick="openPayment('${x.id}')">${t("paymentAdd")}</button><button class="btn small danger" onclick="delDebtor('${x.id}')">${t("delete")}</button></td></tr>`).join(""):`<tr><td colspan="4" class="empty">${t("noData")}</td></tr>`}</table></div>`}
function expensesPage(){return `<div class="section-head"><button class="btn" onclick="openModal('expense')">${t("newExpense")}</button></div><div class="table-wrap"><table class="table"><tr><th>${t("date")}</th><th>${t("expenseName")}</th><th>${t("amount")}</th><th>${t("note")}</th><th>${t("actions")}</th></tr>${data.expenses.length?data.expenses.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${esc(x.name)}</td><td>${money(x.amount)}</td><td>${esc(x.note||"-")}</td><td><button class="btn small danger" onclick="delExpense('${x.id}')">${t("delete")}</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">${t("noData")}</td></tr>`}</table></div>`}
function reportsPage(){const s=stats();return `<div class="grid">${stat(t("salesTotal"),money(sum(data.sales,x=>x.total)))}${stat(t("purchasesTotal"),money(sum(data.purchases,x=>x.total)))}${stat(t("expensesTotal"),money(sum(data.expenses,x=>x.amount)))}${stat(t("profit"),money(sum(data.sales,x=>x.total)-sum(data.purchases,x=>x.total)-sum(data.expenses,x=>x.amount)))}</div><div class="section card"><h3>${t("monthly")}</h3><p>${t("salesTotal")}: <b>${money(s.sales)}</b></p><p>${t("purchasesTotal")}: <b>${money(s.purchases)}</b></p><p>${t("expensesTotal")}: <b>${money(s.expenses)}</b></p><p>${t("profit")}: <b>${money(s.profit)}</b></p></div>`}
function settingsPage(){return `<div class="card"><div class="form"><div class="field"><label>${t("shopName")}</label><input id="shopName" value="${esc(data.settings.shopName)}"></div><div class="field"><label>${t("language")}</label><select id="langSet"><option value="fa" ${data.settings.lang==="fa"?"selected":""}>دری</option><option value="ps" ${data.settings.lang==="ps"?"selected":""}>پښتو</option><option value="en" ${data.settings.lang==="en"?"selected":""}>English</option></select></div><div class="full"><button class="btn" onclick="saveSettings()">${t("saveSettings")}</button></div></div></div>`}
function modalHTML(){
 let content="",title="";
 if(state.modal==="product"){title=t("newProduct");content=`<form onsubmit="saveProduct(event)" class="form"><div class="field"><label>${t("name")}</label><input name="name" required></div><div class="field"><label>${t("code")}</label><input name="code"></div><div class="field"><label>${t("buyPrice")}</label><input name="buyPrice" type="number" min="0" required></div><div class="field"><label>${t("sellPrice")}</label><input name="sellPrice" type="number" min="0" required></div><div class="field"><label>${t("stock")}</label><input name="stock" type="number" min="0" value="0" required></div><div class="field"><label>${t("minStock")}</label><input name="minStock" type="number" min="0" value="2"></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="sale"){title=t("newSale");content=saleForm()}
 if(state.modal==="purchase"){title=t("newPurchase");content=`<form onsubmit="savePurchase(event)" class="form"><div class="field"><label>${t("product")}</label><select name="productId" required>${data.products.map(p=>`<option value="${p.id}">${esc(p.name)} (${p.stock})</option>`).join("")}</select></div><div class="field"><label>${t("qty")}</label><input name="qty" type="number" min="1" required></div><div class="field"><label>${t("buyPrice")}</label><input name="price" type="number" min="0" required></div><div class="field"><label>${t("supplier")}</label><input name="supplier"></div><div class="field"><label>${t("payment")}</label><select name="payment"><option value="cash">${t("cash")}</option><option value="credit">${t("credit")}</option></select></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="expense"){title=t("newExpense");content=`<form onsubmit="saveExpense(event)" class="form"><div class="field"><label>${t("expenseName")}</label><input name="name" required></div><div class="field"><label>${t("amount")}</label><input name="amount" type="number" min="0" required></div><div class="field full"><label>${t("note")}</label><input name="note"></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="debtor"){title=t("newDebtor");content=`<form onsubmit="saveDebtor(event)" class="form"><div class="field"><label>${t("name")}</label><input name="name" required></div><div class="field"><label>شماره تماس</label><input name="phone"></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 if(state.modal==="payment"){const d=data.debtors.find(x=>x.id===state.editing);title=t("paymentAdd");content=`<form onsubmit="savePayment(event)" class="form"><div class="notice">${esc(d?.name||"")} — ${money(d?.balance)}</div><div class="field full"><label>${t("paymentAmount")}</label><input name="amount" type="number" min="1" max="${d?.balance||0}" required></div><div class="full"><button class="btn">${t("save")}</button></div></form>`}
 return `<div class="modal-back" onclick="if(event.target===this)closeModal()"><div class="modal"><button class="close" onclick="closeModal()">×</button><h3>${title}</h3>${content}</div></div>`
}
function saleForm(){return `<form onsubmit="saveSale(event)" class="form"><div class="field"><label>${t("product")}</label><select name="productId" required>${data.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.sellPrice)} (موجودی ${p.stock})</option>`).join("")}</select></div><div class="field"><label>${t("qty")}</label><input name="qty" type="number" min="1" required></div><div class="field"><label>${t("customer")}</label><input name="customer"></div><div class="field"><label>${t("payment")}</label><select name="payment"><option value="cash">${t("cash")}</option><option value="credit">${t("credit")}</option></select></div><div class="field"><label>${t("discount")}</label><input name="discount" type="number" min="0" value="0"></div><div class="field"><label>${t("paidNow")}</label><input name="paid" type="number" min="0" value="0"></div><div class="field full"><label>${t("note")}</label><input name="note"></div><div class="full"><button class="btn success">${t("save")} + ${t("print")}</button></div></form>`}
function openModal(m){state.modal=m;state.editing=null;render()}
function closeModal(){state.modal=null;render()}
function saveProduct(e){e.preventDefault();const f=new FormData(e.target);data.products.push({id:uid(),name:f.get("name"),code:f.get("code"),buyPrice:+f.get("buyPrice"),sellPrice:+f.get("sellPrice"),stock:+f.get("stock"),minStock:+f.get("minStock")});save();closeModal()}
function savePurchase(e){e.preventDefault();const f=new FormData(e.target),p=data.products.find(x=>x.id===f.get("productId"));if(!p)return;const qty=+f.get("qty"),price=+f.get("price");p.stock+=qty;data.purchases.push({id:uid(),date:today(),productId:p.id,productName:p.name,qty,total:qty*price,price,supplier:f.get("supplier"),payment:f.get("payment")});save();closeModal()}
function saveSale(e){e.preventDefault();const f=new FormData(e.target),p=data.products.find(x=>x.id===f.get("productId"));if(!p)return;if(p.stock<+f.get("qty")){alert("موجودی کافی نیست");return}const qty=+f.get("qty"),sub=qty*p.sellPrice,discount=+f.get("discount")||0,total=Math.max(0,sub-discount),paid=Math.min(total,+f.get("paid")||0),remaining=total-paid; p.stock-=qty; const sale={id:uid(),billNo:"NR-"+String(data.sales.length+1).padStart(5,"0"),date:today(),customer:f.get("customer"),productId:p.id,items:[{name:p.name,qty,price:p.sellPrice,total:qty*p.sellPrice}],subtotal:sub,discount,total,paid,remaining,payment:f.get("payment"),note:f.get("note")};data.sales.push(sale);if(remaining>0&&f.get("customer")){let d=data.debtors.find(x=>x.name.trim()===f.get("customer").trim());if(!d){d={id:uid(),name:f.get("customer"),balance:0,phone:""};data.debtors.push(d)}d.balance+=remaining}save();state.modal=null;state.printSale=sale;render();setTimeout(()=>window.print(),300)}
function saveExpense(e){e.preventDefault();const f=new FormData(e.target);data.expenses.push({id:uid(),date:today(),name:f.get("name"),amount:+f.get("amount"),note:f.get("note")});save();closeModal()}
function saveDebtor(e){e.preventDefault();const f=new FormData(e.target);data.debtors.push({id:uid(),name:f.get("name"),phone:f.get("phone"),balance:0});save();closeModal()}
function openPayment(id){state.editing=id;state.modal="payment";render()}
function savePayment(e){e.preventDefault();const f=new FormData(e.target),d=data.debtors.find(x=>x.id===state.editing);if(d)d.balance=Math.max(0,d.balance-(+f.get("amount")||0));save();closeModal()}
function delSale(id){if(!confirm(t("confirmDelete")))return;const s=data.sales.find(x=>x.id===id);if(s){s.items.forEach(i=>{const p=data.products.find(p=>p.name===i.name);if(p)p.stock+=i.qty});}data.sales=data.sales.filter(x=>x.id!==id);save();render()}
function delPurchase(id){if(!confirm(t("confirmDelete")))return;const x=data.purchases.find(x=>x.id===id),p=data.products.find(p=>p.id===x?.productId);if(p)p.stock=Math.max(0,p.stock-x.qty);data.purchases=data.purchases.filter(x=>x.id!==id);save();render()}
function delProduct(id){if(confirm(t("confirmDelete"))){data.products=data.products.filter(x=>x.id!==id);save();render()}}
function delDebtor(id){if(confirm(t("confirmDelete"))){data.debtors=data.debtors.filter(x=>x.id!==id);save();render()}}
function delExpense(id){if(confirm(t("confirmDelete"))){data.expenses=data.expenses.filter(x=>x.id!==id);save();render()}}
function saveSettings(){data.settings.shopName=document.getElementById("shopName").value;data.settings.lang=document.getElementById("langSet").value;save();render()}
function printSale(id){state.printSale=data.sales.find(x=>x.id===id);render();setTimeout(()=>window.print(),200)}
function billHTML(s){if(!s)return"";return `<div class="bill"><h2>${esc(data.settings.shopName)}</h2><p>${t("billNo")}: ${s.billNo}</p><p>${s.date}</p><table><tr><th>${t("product")}</th><th>${t("qty")}</th><th>${t("total")}</th></tr>${s.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.qty}</td><td>${money(i.total)}</td></tr>`).join("")}</table><p>${t("subtotal")}: ${money(s.subtotal)}</p><p>${t("discount")}: ${money(s.discount)}</p><p>${t("total")}: ${money(s.total)}</p><p>${t("paid")}: ${money(s.paid)}</p><p>${t("remaining")}: ${money(s.remaining)}</p><p>${esc(s.customer||"")}</p></div>`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
window.go=go;window.setLang=setLang;window.openModal=openModal;window.closeModal=closeModal;window.saveProduct=saveProduct;window.savePurchase=savePurchase;window.saveSale=saveSale;window.saveExpense=saveExpense;window.saveDebtor=saveDebtor;window.openPayment=openPayment;window.savePayment=savePayment;window.delSale=delSale;window.delPurchase=delPurchase;window.delProduct=delProduct;window.delDebtor=delDebtor;window.delExpense=delExpense;window.saveSettings=saveSettings;window.printSale=printSale;
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
render();